backend:
  name: git-gateway
  branch: main

collections:
 - name: "tournaments"
   label: "Tournaments"
   folder: "_events/tournaments"
   create: true
   path: '{{title}}/index'
   fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Level", name: "level", widget: "string" }
    - { label: "Format", name: "format", widget: "string" }