backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: 'tournament'
    label: 'Tournament'
    folder: '_events/tournaments'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Date", name: "date", widget: "datetime" }
    - { label: "Level", name: "level", widget: "string" }
    - { label: "Format", name: "format", widget: "string" }